# Configuration du connecteur Redmine-Email

# Configuration Redmine
redmine:
  url: 'http://localhost:3000/'
  api_key: 'dbc5d3f317cf69e27f2715c91734a64e316ef429'
  api_version: '4.2'
  default_project_id: 1  # ID du projet par défaut

# Configuration email
email:
  server: 'smtp.gmail.com'
  port: 587
  username: 'daaji aymen'
  password: 'Aymen54072088'
  check_interval: 5  # intervalle de vérification des emails en minutes

# Configuration de l'application
app:
  debug: false
  log_level: 'INFO'